# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourprojectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourproject',
            options={'ordering': ['proj_pos']},
        ),
        migrations.AddField(
            model_name='ourproject',
            name='proj_pos',
            field=models.IntegerField(default=1),
        ),
    ]
