# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-15 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourprojectsapp', '0002_auto_20180615_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourproject',
            options={'ordering': ['-proj_pos']},
        ),
    ]
